#########################################################
##              Projet configuration file              ##
#########################################################

# Executable name:
NAME=firmware

COMPILER_DEFINES = -DUSB_DEVICE_ROM_DRIVER

# project source files:
C_PROJECT=usermain.c
# UsbRom.c

# include repertory : -I<repertory path>
INC_PROJECT=

# path to project source code
C_PATH_PROJECT=./source ./usb ./usb/Lib


#### select device you want to use ####
mcu = lpc13xx
hardware = lpc13-dev

#### if you want a minimal kernel, set yes ####
kernelmin = yes

#### kernel memory size, available RAM memory for malloc ####
kernelmemory = 2560

#### select driver you want to use in your firmware ####
debug = yes

# prs sensor use the i2c slave :
prs-sensor = no
i2cslave = yes

gpio = yes

# gpio irq with event :
gpio-irq = yes
kevent = yes

analog = yes
uart0 = yes
utils = yes
pwm = yes
sleep = yes
timer = yes
i2cmastersoft = yes
magnetometer = no
accelerometer = no
mathcos-sin = yes
mathtan = yes

mem-protocol = no
eeprom = no

#### compiler defines ####

# Activate debug trace for kernel
COMPILER_DEFINES += -DKERNEL_USE_DEBUG

# size of kernel stack : don't change !
kernelstacksize = 0x00000200

# compiler optimization:
OPTIMIZE=-Os

#compiler options (CFLAGS):
COMPILER_OPTION	=$(OPTIMIZE)
COMPILER_OPTION += -Wall
COMPILER_OPTION += -Wextra
COMPILER_OPTION += -mthumb
COMPILER_OPTION += -mcpu=cortex-m3
COMPILER_OPTION	+= -mtune=cortex-m3
COMPILER_OPTION	+= -march=armv7-m
#COMPILER_OPTION	+= -mapcs-frame
#COMPILER_OPTION	+= -msoft-float
#COMPILER_OPTION += -mno-sched-prolog
#COMPILER_OPTION += -fno-hosted
#COMPILER_OPTION	+= -mfix-cortex-m3-ldrd
COMPILER_OPTION += -ffunction-sections
COMPILER_OPTION	+= -fdata-sections
COMPILER_OPTION += -fno-builtin

# Activate debug for jtag :
# COMPILER_OPTION += -ggdb 

#linker options (LDFLAGS):
LINKER_OPTION =-T$(LINK_HW)
LINKER_OPTION += -nostartfiles
LINKER_OPTION += -Wl,-Map=$(BUILD_PATH)/main.map,--cref,-nostdlib
LINKER_OPTION += -static
LINKER_OPTION += -mcpu=cortex-m3
LINKER_OPTION += -mthumb
#LINKER_OPTION += -mthumb-interwork
LINKER_OPTION += -lc
LINKER_OPTION += -lgcc
LINKER_OPTION += -lm

# assembler options:
ASM_OPTIONS =-mthumb
ASM_OPTIONS += -mcpu=cortex-m3 --defsym Kernel_Stack_Size=$(kernelstacksize)



# path to Dvos and libs-hardware source directory:
DVOS_PATH=../../dvos/
